### PR TITLE
Clean up PHP, show and hide buttons and form as needed.

### PR DESCRIPTION
**Pull request by jmhobbs**
Tames the mess of nested PHP & HTML, and shows hides the form and button as needed.
## Initial Load
- `<a>`
- `<form class=collapsed>`
## Form Submitted, Error
- `<div class="form-result error">`
- `<form>`
## Form Submitted, Success
- `<div class="form-result success">`

### CODE REVIEW

**Comment by jmhobbs** [comment]
I rebased and force pushed.  It's a clean merge now, no rush on it, doesn't change any behaviors.

**Comment by zachleat** [comment]
what happened :(

**Comment by jmhobbs** [comment]
Ala-kazam!  History is rewritten.

No rush merging this.  It's for my own satisfaction only.

**Comment by zachleat** [comment]
I merged but I didn’t test it sooooooo

¯_(ツ)_/¯

**Comment by jmhobbs** [comment]
lol, is it live?

**Comment by jmhobbs** [comment]
If it is, live is working fine.  :)

**Comment by zachleat** [comment]
No, this was merged but not pushed live.

**Comment by zachleat** [comment]
So, ticking time bomb maybe

**Comment by jmhobbs** [comment]
More like ticking time awesome!

Let me know when you push it and I'll check it out.  Works fine locally, no reason it should break in prod.

**Pull request merged**
